language: java
sudo: false
notifications:
  hipchat:
    rooms:
      secure: OlIO4DA0xfqdHqS2ytSfDucjIoncHBgLDFjDi1u+qsLOPBeYpYuNJOZkW531yKPFS/na8BjS5WzjrdZW1Wa2I41X2KdNEqOBPxCNsDlvRzEsMUXGCekTEkIaVKgyD8LsAqku+I0CFRsYCQCxRz6yufEenDf7VwdhbM/345mopkI=
deploy:
  provider: releases
  api_key:
    secure: UpHxmny7Lu2dyRuZuOkVfx98z0XwJXZlTwMhCGUqfMC9DrfHFyr4jbeDLoVIxJ9fB3srMquwmfJ3zzoBNKiukCqp2EKEP6xDRLnUAsL2OyFgXfQc6xV8edxxEVs1SXRozX9sa852dvpqr0oZzgSTW74VGMma97HtY6zdSz3a+c9rIb9u8n0tFcAkdE/vB1Sa1hbr+PYe+IwC5bMl41hs+aFoD5sWdnY1LvRsgQDABRue461l26CkTbqIIC/o/d6pw83FP2sTeCOtJYmuaMsy4TvJJTvdrzLzph4srRP9gWZsUUSFvsvNg4lXangzoZY1D9YpT7Axua19dci+qjaIU/TNa037PPBlypCiNvL71jDTGRGI6y8wNcSeDLG0t2ryeOxrzniGmHr/Vfi1VGX3Dx6c6JlhaoPtnJASaRnUXLHsbjPRpz5sTS6xCbdB9rmSVETaMkMugLcAmzQe5nXbKnsgWzdA42t7s5cPVChPEZH88sdmaL2T5Xv+FmOymLlh19VLiWkYnVXEH1JUG4tEMfAkBKbvFCWe7i2R1Gu64LJnr5y/f5H/X0Y2Rkaa3nB/x+SExCJX+x54bbKTaklRfL1AxY/jedgiFgQhXT4nXeN36AWFoAdqoxd08hhSsh/LuYscdg/Avpp0jkfCP4SGIq21QksKVLY85vYJlOBjy9o=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-rundeck-plugin
