language: java
sudo: false
notifications:
  slack:
    secure: FI0eRMIEYImVL6JsoNonZ/EejWUrPP39b4go8G1xgMVxz4CPgGpFJevbDBOfEG6sptVGZqaTMRJOHy6W5L761JADvb+ouAX2a7St/r329IOqaAF+ChPKd9Ia2Y2Zs03X61Bdormwee3ztbxcvZI2LHEbR8XF8N+tqb4iE3o5VV/ATzDb+6WJJvdrL6sQETefZJlMb1Che5uziQfHaR18qfJ/rP74u8IV7X7TLMqQ9TIn4okSecx3veO/5lPkc9j7G7ugWQieUMnHeXWmVyiXORtus6kD0OKM5Ra7NY57B1NdqgaQT9NmG5ufN6HNwrVBNqp7b9k8bW+uROL6BKyV3ymSTStG8k3XuIDVP5BEIvj/OirrHxyQ1o6dWnow+vPt0jPXcAeIWh5MmBsBgaiNnFBPs1bqWAmDFZIxrDa6puy3BRiz/goK+7D2Yjvll5EdRknfr6n/gIDKH6/rK3oTUjCBi/uhycnbKPqG0wUxB7NAWpeK1JKZTdO4rXs70eV4TpC7fDYzcwvAHrirCTMKHT/OVeUajFBEyyCJfiCml3xZocV4PRkybeLv1J/soYBaEkGyLKxaQHAT+2+X4PAaRUJtSfO1yehW5FBddF534dZoveNy3neDAt7qXsN5+Kj/Uhoq0OkdlIP+v+CGMfxym+S1mX68bH2YUVA0qNEkT5k=
deploy:
  provider: releases
  api_key:
    secure: jBvPTDvPsMtmL1BytgE7UnZUU0//yFi6Cssmv5a+Oo4IJSq+z9C86ZiqS9Gs0Q8/sEhdGB03H4T/N/wc1KSptC5jbNNCo2WsligQTYVNyu1hMl/U2gl/prq6UeEUI6VxkStK3Nz+t9q4NJeNEiwqB6dAhU2tIuhqPoou4M0JqGTvks666MOvyGZbtRjdgh2wsfUh7udrMOE3Wlda2UwHYyjpkTHt3V8pyQh0on1fBz20AJb3QyV0J8Zmj4PdkULlvndUyI5R5ur6cj8lm9KNdRDSXLYkWTv0jzrpZtiHnrcE330v2HyPrhrJmYw2wfXFGnDlVDpaJDRtnXT7r3uoJUm5vNt04OAdAeQP481ISSjwkpCcQFQVnVNRQgYMMei0WcNiRPerQ1Gs+5GYoL1ny0Hfy7f5g5xwGWD4Z5k/m8/js73yFf6MA5zXh0WGlOpc59HBqIWYfEA6XF/MFx+WLWZGPRiw4DBODoA1nDOM5LW+xhSD7KOyc3zA0ZqzISHRXy0exmzF+QiLEZfWnysgBCjQTARjEnIUJILQdwcevMu1Viv7CJwNpqVkQxuZhPGLcWYGub6l6CLQw9fJinmRgVDmFc+U3lkLvfbq07JaPRBBK1mXUeLXZ6O4QUrTwj06eihROOFUW9rjLgSMbLezv43nqaSMOL9CzlBhHq4Ifko=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-rundeck-plugin
