language: java
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: A0rtcc5iWVOiKodiYxX8DzNn777k2boUWILXtfEKKXqHzxENYaj5EHeMT+kC+2F/rnnjS79fMFD9VU4d/dbjiQH4wzHMPA5gBGpOpb+q0zbLTxt4sYmn+9HqVoIu774ZSBkX1fh5y/MM6qrjUJbPLMuBylM88PhYu95hGL7TW1w=
deploy:
  provider: releases
  api_key:
    secure: YeVSZcNmrEkWV3cqAQ0+YDJnG7585WVRykHPyx9WuwcjEeWOeQ+UpxypDWDtsMJ/xRXR0qN1G480/6ze5cUP4OM+0Nd3XB33W+0lU3f3+VtmlRoA8eXb6zDfeylN5lGEIYfPdyvUN0rCt7x2QJ1gSjkIz+woaVUGOrDmNh8QCO9BJeHQouRXQFo4QC8cg5/r6cvcpXA1HQLb2syMmxW6K0PTsJeKdFkR8NBkpj3yxJgseaOFe1Ccf9aQ/iAKAEH82ZOqmLeXoleHx8nzHVOpXf6G7fWM6u1BpnArctkN/rDZD6zD7FnnDt6cpIxliA3CCrpt7IkHP/lTLPiPJWxIErkbnOmKTxxdkHp1LddzEGIQye44cmBYs2d9t8qCmr/gowIaLMVAusQ4ZSnOH8QQpVyO5zcFve4TgqvKBKPYdETpPjujz7AZbyeTNUPv0foF5q51QG4Bgy0EF90FUDjy9xtIbzJgVDLHzIehYcRYdZhMh5mCxAgRu8Q718EeOnhlVi9cvDuyTQj1SVhPrAoh0fp98PvAPOEhv/btWLCLZngHLFSOTyWufOtGUpF18/VUdBlwbK0mASLvpkWHU+8f0VRv8ZNoxvoqY4YhfiLDkBKh2uygWw5fnK24hfshPrwZMYE7r2F1P3xy4QjI1uQKbFs8wXFE9py1sr4p8KQc4x8=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-rundeck-plugin
